---
title: speech feedback
author: public speaking club
output:
  html_document:
    css: style.css
    includes:
      after_body: footer.html
always_allow_html: true
params:
  year: "2021"
  month: "10"
  day: "18"
  s: 4
  speechtitle: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10,
  fig.asp = .45,
  out.width = "100%"
)

#######################################   S E T   U P   ##############################################
meeting_date <- as.numeric(paste0(params$year, params$month, params$day))
s <- params$s

####################################   L I B R A R I E S   ###########################################
if (!require(ggplot2)) {install.packages("ggplot2"); library(ggplot2)}
if (!require(stringr)) {install.packages("stringr"); library(stringr)}
if (!require(reshape2)) {install.packages("reshape2"); library(reshape2)}
if (!require(dplyr)) {install.packages("dplyr"); library(dplyr)}
if (!require(ggiraph)) {install.packages("ggiraph"); library(ggiraph)}
if (!require(extrafont)) {install.packages("extrafont"); library(extrafont)}
if (!require(scales)) {install.packages("scales"); library(scales)}
if (!require(reactable)) {install.packages("reactable"); library(reactable)}
if (!require(knitr)) {install.packages("knitr"); library(knitr)}                # asis_output function 

###############################   C O L O U R S   &   T H E M E   #####################################
RM_colours <- colorRampPalette(c("#497367", "#a6c4b8", "#d0b3af", "#c58198"))
col_rating <- c("Excels" = RM_colours(4)[1], "Accomplished" = RM_colours(4)[2],
                "Developing" = RM_colours(4)[3], "Beginning" = RM_colours(4)[4] )
font <- "Lato"
font_bold <- font
fontsize <- 17.8
extrafont::loadfonts(device = "win", quiet = TRUE)
theme_set(theme_minimal(base_size = fontsize) %+replace% theme(
      rect = element_rect(fill = "transparent"),
      plot.title = element_blank(),
      plot.margin = unit(c(0,20,15,0), "pt"),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      axis.title.x = element_text(family=font_bold, size = rel(0.70), vjust = -5),
      axis.title.y = element_blank(),
      axis.text = element_text(family=font, size = rel(0.70)),
      legend.position = "top",
      legend.text.align = 0,
      legend.title = element_blank(),
      legend.text = element_text(family=font, size = rel(0.70)),
      legend.key = element_rect(fill = "transparent", colour = NA),
      legend.key.size = unit(1.5, "lines"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      legend.box.spacing = unit(0, "pt"),
      # facet options
      strip.background = element_rect(fill = "#17252D", color = "#17252D"),
      strip.text = element_text(size = rel(0.85), face = "bold", color = "white", margin = margin(5,0,5,0))
    )
)
# language settings 
Sys.setlocale("LC_ALL","English_United Kingdom")

###############################   L O A D   D A T A   #####################################
speech_feedback <- read.csv(paste0("csv_files/speech_feedback_",meeting_date,".csv"), stringsAsFactors = FALSE)
names(speech_feedback) <- c("Time", "Speaker", "Clarity", "VocalVariety", "EyeContact", "Gestures", "Interest", "Liked", "Improve", "Name")

# extract speech date
speech_date <- str_sub(speech_feedback$Time, 1 , str_locate(speech_feedback$Time, pattern = " ")[1]-1) %>% as.Date(tryFormats = c("%d.%m.%Y", "%d/%m/%Y", "%d-%m-%Y", "%m/%d/%Y", "%m-%d-%Y", "%Y/%m/%d")) %>% min %>% format("%e %B %Y") %>% str_trim
speech_d <- str_sub(speech_date, 1, str_locate(speech_date, " ")[1]-1)
speech_d2 <- str_sub(speech_d, nchar(speech_d))
speech_mY <- str_sub(speech_date, str_locate(speech_date, " ")[1]+1, nchar(speech_date))
day_ord <- case_when(speech_d2 == "1" ~ "st", speech_d2 == "2" ~ "nd", speech_d2 == "3" ~ "rd", TRUE ~ "th")
speech_date <- paste(paste0(speech_d, day_ord), speech_mY)

# remove duplicate entries
speech_feedback <- unique(speech_feedback[, 2:ncol(speech_feedback)])
rating_names <- c("Clarity: Spoken language is clear and is easily understood",
  "Vocal Variety: Uses tone speed and volume as tools",
  "Eye Contact: Effectively uses eye contact to engage audience",
  "Gestures: Uses physical gestures effectively",
  "Interest: Engages audience with interesting well constructed content")[5:1]
evaluation_names <- c("Liked about the speech",
  "What could be improved",
  "Name")
rating <- c("Excels","Accomplished","Developing","Beginning")
category <- c("Interest","Gestures","EyeContact","VocalVariety", "Clarity")
titles <- c()
speech_feedback_list <- split(speech_feedback, speech_feedback$Speaker)
speakers <- names(speech_feedback_list)

speaker <- list()
speaker$rating <- speech_feedback_list[[s]][,c(2:6,9)]
speaker$evaluation <- speech_feedback_list[[s]][,c(7:9)] %>% subset(.$Liked != "" | .$Improve != "") %>% setNames(evaluation_names)
speaker$rating_melt <- melt(speaker$rating, id.vars = c("Name"), variable.name = "Category", value.name = "Rating",
                            measure.vars = c("Clarity", "VocalVariety", "EyeContact", "Gestures", "Interest")) %>%
  subset(is.na(.$Rating)==FALSE & .$Rating!="") %>% 
  mutate(Rating = factor(Rating, levels = rating), Category = factor(Category, levels = category),
         Rating_num = recode(Rating, "Excels"=4, "Accomplished"=3, "Developing"=2, "Beginning"=1),
         Category_Rating = paste(Category, Rating, sep = "_"))
speaker$rating_dcast <- dcast(speaker$rating_melt, Category ~ Rating) # %>% mutate(Total = rowSums(.[,2:ncol(.)]))
speaker$rating_melt2 <- melt(speaker$rating_dcast, id.vars = "Category", variable.name = "Rating", value.name = "Rating_perc") %>%
  mutate(Rating_perc = case_when(Rating_perc == 1 ~ paste(Rating_perc, "attendee"), TRUE ~ paste(Rating_perc, "attentees")))
speaker$rating_melt <- left_join(speaker$rating_melt, speaker$rating_melt2, by = c("Category", "Rating"))

if (str_detect(speakers[s], " - ")) {
  titles[s] <- str_sub(speakers[s], str_locate(speakers[s], " - ")[2]+1, nchar(speakers[s]))
  speakers[s] <- str_sub(speakers[s], 1, str_locate(speakers[s], " - ")[1]-1) 
} else {
    speakers[s]
  titles[s] <- params$speechtitle}

showtitle <- is.na(titles[s]) == FALSE
```

<center>

### speech feedback for 

# `r speakers[s]`

```{r, eval = showtitle}
asis_output((paste0("##### ", titles[s], "\\n")))
```

## `r speech_date`

</center>

#### How attendees evaluated your speech:
  
```{r}
plot_rating <- ggplot() + geom_bar_interactive(speaker$rating_melt, mapping = aes(x = ..count../sum(..count..)*5, y = speaker$rating_melt$Category, fill = speaker$rating_melt$Rating, data_id = speaker$rating_melt$Category_Rating,
                                                                                                 tooltip = Rating_perc), 
                    alpha = 1, colour = "white", size = 4, width = .7) +
  scale_x_continuous(labels=scales::percent, expand = c(0,0), name = "Percentage of attendees evaluating speech elements") +
  scale_fill_manual(values = col_rating, breaks = c("Excels","Accomplished","Developing","Beginning")[4:1]) +
  scale_y_discrete(labels = str_wrap(rating_names, 35))
tooltip_css <- paste(paste0("font-family:",font), paste0("font-weight:","bold"), paste0("font-size:",fontsize*.8,"px"), sep = ";")
ggiraph(code = {print(plot_rating)}, width_svg = 8.8, height_svg = 4,
        tooltip_extra_css = tooltip_css, hover_css = "r:10pt;opacity:.8" ) 
```

#### What attendees liked about the speech and their suggestions:

```{r speaker$evaluation}
reactable(speaker$evaluation, sortable = FALSE, highlight = TRUE, columns = list(Name = colDef(maxWidth = 100)), pagination = FALSE)
```